In [ ]:
#creating array using numpy
#create 1D array

import numpy as np
arra1=np.array([1,2,3,4,5,6])
print(arra1)
print(type(arra1))
print(np.shape(arra1))

In [7]:
#creating 2D array
import numpy as np
arra2=np.array([[1,2,3],[2,4,5]])
print(type(arra2))
print(np.shape(arra2))

<class 'numpy.ndarray'>
(2, 3)


In [12]:
lst=[x for x in range(1,11)]
print(lst)
import numpy as np
np.arange(0,20,3)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


array([ 0,  3,  6,  9, 12, 15, 18])

In [15]:
np.ones(2)

array([1., 1.])

In [17]:
#identity matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#Atrributes of numpy array
arr=np.array([[22,33,44],[123,42,56]])
print("Array:\n",arr)
print("Shape:",arr.shape)
print("NUmber of dimension:",arr.ndim)
print("Number of elements:",arr.size)
print("Data type:",arr.dtype)
print("Item size(in byte):",arr.itemsize)

Array:
 [[ 22  33  44]
 [123  42  56]]
Shape: (2, 3)
NUmber of dimension: 2
Number of elements: 6
Data type: int64
Item size(in byte): 8


In [26]:
# Statistical concepts in Numpy
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 60, 90],
                [10, 20, 20]])

mean = np.mean(arr)
print("Mean:", mean)

median = np.median(arr)
print("Median:", median)

st_dev = np.std(arr)
print("Standard Deviation:", st_dev)

variance = np.var(arr)
print("Variance:", variance)


Mean: 40.0
Median: 35.0
Standard Deviation: 24.8327740429189
Variance: 616.6666666666666


In [27]:
#logical operations
# Statistical concepts in Numpy
import numpy as np

arr = np.array([1,2,3,5,6,7,46,3,44])
arr>5


array([False, False, False, False,  True,  True,  True, False,  True])