### Assignment 1: Array Creation and Manipulation
1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20.
Replace all the elements in the third column with 1.

In [ ]:
import numpy as np
array = np.random.randint(1,99,size=(5,5))  
print(array)

#replacing the elements of third column
array[:,2] = 1
print("After: ")
print(array)


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. 
Replace the diagonal elements with 0.

In [ ]:

array=np.random.randint(1,17,size=(4,4))
print("Array before: ")
print(array)
#fill diagnoal with 0
np.fill_diagonal(array,0)
print("Array after: ")
print(array)

Create a NumPy array of shape (6, 6) with values from 1 to 36. 
Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [ ]:
new_array=np.random.randint(1,37,size=(6,6))
print(new_array)
print("Sub Array")
third_array=new_array[2:5, 1:4]
print(third_array)

Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [ ]:
array=np.random.randint(1,99,size=(5,5))
print(array)
#extracting elements from the border 
# Top and bottom rows
top = array[0, :]
bottom = array[-1, :]

# Left and right columns (excluding corners already in top/bottom)
left = array[1:-1, 0]
right = array[1:-1, -1]

# Combine all border elements
border = np.concatenate([top, right, bottom[::-1], left[::-1]])
print("\nBorder Elements:")
print(border)


Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, 
subtraction, multiplication, and division.

In [5]:
import numpy as np
array1=np.random.randint(1,99,size=(3,4))
array2=np.random.randint(1,99,size=(3,4))
addition=array1+array2
subtraction=array1-array2
multiplication=array1*array2
division=array1/array2
print("Addition: ")
print(addition)
print("Subtraction:")
print(subtraction)
print("Multiplication: ")
print(multiplication)
print("Division: ")
print(division)

Addition: 
[[142  86 103 128]
 [ 93  60 128 107]
 [117 119 146 139]]
Subtraction:
[[ 54  68 -19 -48]
 [ 65  38  40  75]
 [ 23 -57  50 -47]]
Multiplication: 
[[4312  693 2562 3520]
 [1106  539 3696 1456]
 [3290 2728 4704 4278]]
Division: 
[[2.22727273 8.55555556 0.68852459 0.45454545]
 [5.64285714 4.45454545 1.90909091 5.6875    ]
 [1.4893617  0.35227273 2.04166667 0.49462366]]


Create a NumPy array of shape (4, 4) with values from 1 to 16. 
Compute the row-wise and column-wise sum.

In [11]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16
array = np.arange(1, 17).reshape((4, 4))
print("Original array:")
print(array)

# Compute the row-wise and column-wise sum
row_sum = np.sum(array, axis=1)
column_sum = np.sum(array, axis=0)

print("Row-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(column_sum)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-wise sum:
[10 26 42 58]
Column-wise sum:
[28 32 36 40]


Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, 
standard deviation, and variance of the array.

In [15]:
array=np.random.randint(1,51,size=(5,5))
mean=np.mean(array)
print("The mean is array: ",mean)
median=np.median(array)
print("The median: ", median)
std=np.std(array)
print("Standard deviation: ",std)
variance=np.var(array)
print("Variance: ",variance)

The mean is array:  31.44
The median:  36.0
Standard deviation:  14.167794464912312
Variance:  200.72639999999996


Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array
(i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [45]:
import pandas as pd 
array=np.random.randint(1,10,size=(3,3))
print("Array:")
print(array)
mean=np.mean(array)
std=np.std(array)
print("After Normalization: ")
normalized_array=(array-mean)/std
print(normalized_array)


Array:
[[9 6 4]
 [6 5 9]
 [4 7 4]]
After Normalization: 
[[ 1.59099026  0.         -1.06066017]
 [ 0.         -0.53033009  1.59099026]
 [-1.06066017  0.53033009 -1.06066017]]


Create a NumPy array of shape (3, 3) filled with random integers.
Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [ ]:
array=np.random.randint(1,99,size=(3,3))
print("Array: ")
print(array)
print("Array to add")
array_1d=np.array([1,23,44])
print(array_1d)
sum=array+array_1d
print(sum)

Array: 
[[69 79 60]
 [19  2 49]
 [48 95 67]]
Array to add
[[ 70 102 104]
 [ 20  25  93]
 [ 49 118 111]]


Create a NumPy array of shape (4, 4) filled with random integers. 
Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [53]:
array1=np.random.randint(1,100,size=(4,4))
print("Main Array: ")
print(array1)
array_1d=np.array([1,3,55,93])
print("1D Array: ")
print(array_1d)
print("Subtraction using broadcasting")
subt=array1-array_1d
print(subt)

Main Array: 
[[53 43  2 89]
 [64  6 88 14]
 [86 59 83 40]
 [ 1 40 22 39]]
1D Array: 
[ 1  3 55 93]
Subtraction using broadcasting
[[ 52  40 -53  -4]
 [ 63   3  33 -79]
 [ 85  56  28 -53]
 [  0  37 -33 -54]]
