Create a 4x4 matrix of random integers and extract the diagonal.

In [9]:
import numpy as np
matrix=np.random.randint(11,99,size=(4,4))
print("4x4 Random Integer Matrix:")
print(matrix)
diagonal=np.diag(matrix)
print("The diagonal elements of the matrix: ", diagonal)

4x4 Random Integer Matrix:
[[67 84 73 85]
 [68 54 45 59]
 [13 85 82 64]
 [90 26 22 12]]
The diagonal elements of the matrix:  [67 54 82 12]


Simulate 1000 Coin Flips Using NumPy

In [10]:
import numpy as np
# 1 for heads and 0 for tails

coin_flips=np.random.choice([0,1],size=1000)
head_count=np.sum(coin_flips)
tail_count=1000-head_count
print(f"Total head counts:{head_count}")
print(f"Total tail count:{tail_count}")

Total head counts:503
Total tail count:497


In [12]:
import pandas as pd
