In [ ]:
import numpy as np



### creating arrays from list 

In [ ]:
array_1d=np.array([1,2,3,4])
print("1D Array: ",array_1d)
array_2d=np.array([[1,2,34],[12,4,5],[22,4,5]])
print("2D Array: ",array_2d)

### List VS Numpy Array

In [ ]:
py_list=[1,12,4,4]
print("This is normal list in python: ", py_list)
print("Python list multiplication: ",py_list *2)

#numpy multiplication
np_array=np.array([1,2,3,4,5]) #performs element-wise multiplication
print("Array Multiplication: ",np_array*2)

import time
start=time.time()
py_list=[i*2 for i in range(1000000)]
print("\n List operation time: ",time.time()-start)

start=time.time()
np_list=np.arange(1000000) * 2
print("\n Numpy operation time: ",time.time()-start)


### creating array from scratch 

In [ ]:
#creating array with zero's
zeros=np.zeros((3,4))
print("Zeros array: \n",zeros)

#creating array with one's
ones=np.ones((3,5))
print("Ones array: \n",ones)

#creating arrays of constant
full=np.full((2,2),7)
print("Full array: \n",full)

#creating arrays of random numbers #floating values
random=np.random.random((4,3))
print("Random array: \n",random)

#creating array with int random values 
randoms=np.random.randint(0,11,size=(3,4))
print("Random array: \n",randoms)

#creating 1d array with arrange
sequence=np.arange(0,11,2)
print("1d  array: \n",sequence)

## Vector, MAtrices and Tensor

In [ ]:
vector=np.array([1,2,3,4])
print("Vector: ",vector)

matrix=np.array([
    [1,2,3],
    [12,4,5]
])
print("Matrices: \n",matrix)


xtensor = np.array([
    [[3, 4, 57], [22, 33, 45]],
    [[33, 44, 453], [33, 5, 73]],
    [[2, 33, 4], [3, 5, 6]]
])
print("Tensor: \n",xtensor)



# Array properties

In [ ]:
arr=np.array([
    [1,2,3],
    [2,3,4]
])
print("Shape: ",arr.shape)
print("Dimension: ",arr.ndim)
print("Data Type:",arr.dtype)
print("Size: ",arr.size)


# Array reshaping

In [ ]:
arr=np.arange(12)
print("Original array: ",arr)
reshaped=arr.reshape(4,3)
print("Reshaped array: \n",reshaped)
flattened=reshaped.flatten()
print("Flattened Array: ",flattened)
revaled=arr.ravel()

# Transpose

In [50]:
transposed=reshaped.T
print(transposed)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
